2017Q2アニメの追加 ref #67
anilogia/animedb pull request #69
Opened 2017-05-06 09:04 UTC by eru

annictから取得したデータをベースに、 #67 に記載のしょぼかるから調べた開始日を追加したデータ

2017-05-06 16:17 UTC, builtinnya requested changes

2017-05-06 16:17 UTC, builtinnya commented on animedb.yml
> +  title: デュエル・マスターズ (新シリーズ)
しょぼカルや[ニコニコ動画](http://www.nicovideo.jp/watch/1490953789) の表記と同じく「デュエル・マスターズ (2017)」じゃ駄目なんだっけ？

2017-05-06 16:17 UTC, builtinnya commented on animedb.yml
> +  ruby: ベイブレードバーストゴット
ruby は `s/ベイブレードバーストゴット/ベイブレードバーストゴッド/` な気がする

2017-05-06 16:17 UTC, builtinnya commented on animedb.yml
> +  ruby: スタミュ ダイニキ
第2期は suffix にもってた方が良いかなぁ

```yaml
title: スタミュ
suffix: 第2期
ruby: スタミュ
```

2017-05-06 16:17 UTC, builtinnya commented on animedb.yml
> +  started_day: 5
[公式サイト](http://www.fagirl.com/onair.html) によると，4/3 25:05〜 が最速なので 4/4 だよね

2017-05-06 16:17 UTC, builtinnya commented on animedb.yml
> +  suffix:
これも「第2シリーズ 」は suffix に分けた方が良さ気．後，第1シリーズと表記を一致させたい（公式サイトを見るとどこにスペースが入るかは統一されていない）．

```yaml
title: 少年アシベ GO! GO! ゴマちゃん
suffix: 第2シリーズ
```

2017-05-06 16:17 UTC, builtinnya commented on animedb.yml
> +  ruby: ボルト ナルトネクストジェネレーション
`s/ボルト ナルトネクストジェネレーション/ボルト ナルトネクストジェネレーションズ/`

2017-05-06 16:17 UTC, builtinnya commented on animedb.yml
> +  suffix:
これも suffix に分けたい．後，しょぼカルでは「第2シリーズ」と表記しているが[公式サイトだと「第2期」という表記が見られる](http://neco-neco.jp/music.html)ので，そうしたい．

```yaml
title: ねこねこ日本史
suffix: 第2期
```

ちなみに，これは本 PR に含める必要はないが，第1期のタイトルが「ねこねこ本史」になっていて「日」が抜けている

2017-05-06 16:17 UTC, builtinnya commented on animedb.yml
> +  ruby: ブソウショウジョマキャェリズム
`s/ブソウショウジョマキャェリズム/ブソウショウジョマキャヴェリズム/`

2017-05-06 16:17 UTC, builtinnya commented on animedb.yml
> +  started_day:
[4月7日から放送開始](http://twinangel-break.com/)

2017-05-06 16:17 UTC, builtinnya commented on animedb.yml
> +  ruby: ベルセルク ダイニキ
こちらも「第2期」を suffix へ．

```yaml
title: ベルセルク
suffix: 第2期
ruby: ベルセルク
```

2017-05-06 16:17 UTC, builtinnya commented on animedb.yml
> +  ruby: キョウカイノリンネダイサンシリーズ
これもこっちの方が良さ気．

```yaml
title: 境界のRINNE
suffix: 第3シリーズ
ruby: キョウカイノリンネ
```

第2シリーズについて「第2期」と書いてあるが，ここをどちらに統一するかは議論の余地あり．公式では「シリーズ」と呼んでいる．

2017-05-06 16:17 UTC, builtinnya commented on animedb.yml
> +  title: Re:CREATORS (レクリエイターズ)
「(レクリエイターズ)」いらないかも

2017-05-06 16:17 UTC, builtinnya commented on animedb.yml
> +  ruby: ケンカバンチョウオトメ
ruby に「ガールビーツボーイズ」いれた方が良いかも

2017-05-08 10:47 UTC, eru commented
基本的にレビューで指摘された内容は、annictから取得してきたデータをそのまま引用したことに起因するものでした。

個別に返信書くと見難いので、必要部分だけ引用して返信

> しょぼカルやニコニコ動画 の表記と同じく「デュエル・マスターズ (2017)」じゃ駄目なんだっけ？

特に問題ないので、そのように修正しました。

> ちなみに，これは本 PR に含める必要はないが，第1期のタイトルが「ねこねこ本史」になっていて「日」が抜けている

せっかくなので修正しました。

> 第2シリーズについて「第2期」と書いてあるが，ここをどちらに統一するかは議論の余地あり．公式では「シリーズ」と呼んでいる．

「第2期」の方も「シリーズ」と改めました。

2017-05-08 13:14 UTC, builtinnya approved these changes

2017-05-08 13:14 UTC, builtinnya commented
L ❤️ G ❤️ T ❤️ M ❤️

2017-05-08 13:15 UTC, merged