:tada: add 2017Q4 animations
anilogia/animedb pull request #73
Opened 2018-06-01 22:48 UTC by eru

http://uzurainfo.han-be.com/17a.html

2018-06-02 09:44 UTC, honeshabri requested changes
読みや日付を指摘。
あと『THE IDOLM@STER Prologue SideM -Episode of Jupiter-』が無い。

2018-06-02 09:44 UTC, honeshabri commented on animedb.yml
> +    liter
イーブルオアライブ

2018-06-02 09:44 UTC, honeshabri commented on animedb.yml
> +    liter
14

2018-06-02 09:44 UTC, honeshabri commented on animedb.yml
> +    liter
4
地上波よりインターネットでの配信のほうが1日早い

2018-06-02 09:44 UTC, honeshabri commented on animedb.yml
> +  title: 食戟のソーマ 餐の皿
餐ノ皿

2018-06-02 09:44 UTC, honeshabri commented on animedb.yml
> +  started_day: 7
6
南海放送の方が早い

2018-06-02 09:44 UTC, honeshabri commented on animedb.yml
> +  ruby: ラブコメ ウィラブライス ニキサク
ウィーラブライス

2018-06-02 09:44 UTC, honeshabri commented on animedb.yml
> +  started_month: 10
8
ネット配信は8/23から

2018-06-02 09:44 UTC, honeshabri commented on animedb.yml
> +  started_day: 6
23

2018-06-02 09:44 UTC, honeshabri commented on animedb.yml
> +  ended_month: 12
11

2018-06-02 09:44 UTC, honeshabri commented on animedb.yml
> +  ended_day: 22
8

2018-06-02 09:44 UTC, honeshabri commented on animedb.yml
> +  ended_day: 26
27

2018-06-02 09:44 UTC, honeshabri commented on animedb.yml
> +  ended_year: 2018
2017
TBSで2017/12/22に最終話を放映している

2018-06-02 09:44 UTC, honeshabri commented on animedb.yml
> +  ended_month: 1
12

2018-06-02 09:44 UTC, honeshabri commented on animedb.yml
> +  ended_day: 6
22

2018-06-02 11:16 UTC, eru commented on animedb.yml
> +    liter
どこ？

2018-06-02 11:16 UTC, eru commented on animedb.yml
> +    liter
これもどこ？

2018-06-02 11:16 UTC, eru commented on animedb.yml
> +    liter
これもどこ？

2018-06-02 11:26 UTC, eru commented
@honeshabri 0274e94 の終了日のチェックもよろしく

2018-06-02 11:33 UTC, eru commented on animedb.yml
> +    liter
わかった

2018-06-02 12:40 UTC, honeshabri commented on animedb.yml
> +    liter
『僕の彼女がマジメ過ぎるしょびっちな件』の終了日

2018-06-02 12:42 UTC, honeshabri commented on animedb.yml
> +    liter
『URAHARA』の放映開始日が10/5→10/4

2018-06-03 02:15 UTC, honeshabri requested changes
終了日の修正

2018-06-03 02:15 UTC, honeshabri commented on animedb.yml
> +  ended_year: 2017
終了日は2018/3/31

2018-06-03 02:15 UTC, honeshabri commented on animedb.yml
>    started_day: 1
4/1 24:00〜24:30に放送なので4/2とするべき

2018-06-03 02:15 UTC, honeshabri commented on animedb.yml
> +  ended_month: 5
最終回最速は3/25

2018-06-03 02:15 UTC, honeshabri commented on animedb.yml
> +  ended_day: 24
25
BSでは最終話が未放送で24日が最終日となっていた

2018-06-03 02:15 UTC, honeshabri commented on animedb.yml
> +  ended_month: 2
終了日は3/27

2018-06-03 02:15 UTC, honeshabri commented on animedb.yml
> +  ended_month: 7
最速は6/23
WOWOWプライムは初回が一挙2話だったので他の局より1週間早い

2018-06-03 02:15 UTC, honeshabri commented on animedb.yml
> +  ended_day: 1
23

2018-06-03 02:15 UTC, honeshabri commented on animedb.yml
> +  ended_day: 13
終了日は12/23

2018-06-05 15:16 UTC, builtinnya commented
@honeshabri Approve or not?

2018-06-05 21:04 UTC, honeshabri approved these changes

2018-06-11 23:46 UTC, merged